#spring.security.enabled=false
#enabled_plugins.security=false
#security.basic.enabled=false
#nacos.security.ignore.urls=/**
#enabled_plugins.metrics.export.elastic.host=http://localhost:9200
# metrics for prometheus
management.endpoints.web.exposure.include=*

# metrics for elastic search
#enabled_plugins.metrics.export.elastic.enabled=false
#enabled_plugins.metrics.export.elastic.host=http://localhost:9200

# metrics for influx
#enabled_plugins.metrics.export.influx.enabled=false
#enabled_plugins.metrics.export.influx.db=springboot
#enabled_plugins.metrics.export.influx.uri=http://localhost:8086
#enabled_plugins.metrics.export.influx.auto-create-db=true
#enabled_plugins.metrics.export.influx.consistency=one
#enabled_plugins.metrics.export.influx.compressed=true