version: '3'
name: rocketmq-nameserver
services:
  nameserver:
    image: apache/rocketmq:5.1.3 # apache/rocketmq:5.1.3
    container_name: rocketmq-nameserver
    hostname: namesrv
    # 解决日志文件权限不足
    user: root
    ports:
      - "9876:9876"
    volumes:
      - ./logs/:/home/rocketmq/logs/
      - ./conf/:/home/rocketmq/rocketmq-5.1.3/conf/
    command: sh mqnamesrv -c ../conf/namesrv.conf