server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  # 已与挂载目录相对应，如无必要，请勿更改
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log
