# 绑定的IP
bind 0.0.0.0

# 是否开启保护模式
protected-mode no

# 监听的端口
port 6306

tcp-backlog 511

timeout 0

tcp-keepalive 300

# 是否开启守护进程
daemonize no

supervised no

# pid文件位置
pidfile /run/redis/redis.pid

# 日志等级
loglevel notice

# 日志文件位置
logfile "/data/redis.log"

# 数据库个数
databases 1

always-show-logo yes

stop-writes-on-bgsave-error yes

rdbcompression yes

rdbchecksum yes

rdb-del-sync-files no

# 持久化文件放置位置
dir /data/

# Redis默认开启RDB持久化
# RDB文件名称
dbfilename dump.rdb
# RDB持久化保存规则
save 900 1
save 300 10
save 60 10000

# 开启AOF持久化
appendonly yes
# AOF文件名称
appendfilename "appendonly.aof"

replica-serve-stale-data yes

replica-read-only yes

repl-diskless-sync no

repl-diskless-sync-delay 5

repl-diskless-load disabled

repl-disable-tcp-nodelay no

replica-priority 100

acllog-max-len 128

# 默认用户密码，如果配置了ACL，此密码不起作用
requirepass redis

# ACL（Access Control List 访问控制列表）文件位置
# aclfile /etc/redis/users.acl

lazyfree-lazy-eviction no
lazyfree-lazy-expire no
lazyfree-lazy-server-del no
replica-lazy-flush no

lazyfree-lazy-user-del no

# 是否启动集群模式
cluster-enabled yes
# 集群节点信息文件位置
cluster-config-file /usr/local/etc/redis/nodes.conf
# 节点离线的超时时间
cluster-node-timeout 15000
# 集群节点间访问用户
# masteruser zero
# 集群节点间访问密码
masterauth redis

appendfsync always
# appendfsync everysec
# appendfsync no

no-appendfsync-on-rewrite no

auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb

aof-load-truncated yes

aof-use-rdb-preamble yes

lua-time-limit 5000

slowlog-log-slower-than 10000

slowlog-max-len 128

latency-monitor-threshold 0

notify-keyspace-events ""

hash-max-ziplist-entries 512
hash-max-ziplist-value 64

list-max-ziplist-size -2

list-compress-depth 0

set-max-intset-entries 512

zset-max-ziplist-entries 128
zset-max-ziplist-value 64

hll-sparse-max-bytes 3000

stream-node-max-bytes 4096
stream-node-max-entries 100

activerehashing yes

client-output-buffer-limit normal 0 0 0
client-output-buffer-limit replica 256mb 64mb 60
client-output-buffer-limit pubsub 32mb 8mb 60

hz 10

dynamic-hz yes

aof-rewrite-incremental-fsync yes

rdb-save-incremental-fsync yes

jemalloc-bg-thread yes
